### ISSUE TITLE
Confirm that demos work

### ISSUE THREAD

**Issue by laurahlark** [B612-Asteroid-Institute/adam#15]

**Comment by samotiwala** [comment]
Is this to also add a workaround for paths? I was able to only run the config demo (from a PR) after copying it one level up, and then moved my config.json one level down under demos. I then ran the test_single_batch_run.py script under demos fine.

**Comment by laurahlark** [comment]
Hm, yes, but I think there already is one - it's in the README here: https://github.com/B612-Asteroid-Institute/adam (export PYTHONPATH=/path/to/adam/:$PYTHONPATH). Did that work for you? I thought it worked for me, but I also might have accidentally 'fixed' my installation some other way.

**Comment by samotiwala** [comment]
Ah I see. It didn't but I could have done something wrong. Either way, the relative path should be the same since it's all in the same repository workspace? So if adam is one level up from the demos, the path should be `export PYTHONPATH=../:$PYTHONPATH`or something like that, and it would be good to include it in the notebooks.

**Comment by laurahlark** [comment]
I think it's meant to be absolute path - for me, I ran this (well actually added it to my .bash_profile):

export PYTHONPATH="/Users/lauralark/Documents/GitHub/adam:$PYTHONPATH"

That way it'll work whether you're in demos, the top level folder, or a different folder (e.g. the analysis folders)

**Comment by samotiwala** [comment]
Ah, I see what you are saying. You can go two routes: add a path for each demo notebook that is relative to the adam path, or just add one path to your bash profile that takes care of it all, which is probably easier/cleaner. Thanks for clearing it up.

**Comment by laurahlark** [comment]
Yeah of course! All right, notifying UW folks and merging.

**Comment by laurahlark** [comment]
I think this can be closed now. Demos work, integration test are in.
